const GameLetters = {
    "a" : require("@/assets/audio/Main_Menu.m4a"),
    "b" : require("@/assets/audio/Level_1.m4a"),
    "c" : require("@/assets/audio/Level_2.m4a"),
    "d" : require("@/assets/audio/Level_3.m4a"),
    "e" : require("@/assets/audio/Level_4.m4a"),
    "f" : require("@/assets/audio/Level_5.m4a"),
    "g" : require("@/assets/audio/Level_Complete.m4a"),
    "h" : require("@/assets/audio/Level_Complete.m4a"),
    "i" : require("@/assets/audio/Level_Complete.m4a"),
    "j" : require("@/assets/audio/Level_Complete.m4a"),
    "k" : require("@/assets/audio/Level_Complete.m4a"),
    "l" : require("@/assets/audio/Level_Complete.m4a"),
    "m" : require("@/assets/audio/Level_Complete.m4a"),
    "n" : require("@/assets/audio/Level_Complete.m4a"),
    "o" : require("@/assets/audio/Level_Complete.m4a"),
    "p" : require("@/assets/audio/Level_Complete.m4a"),
    "q" : require("@/assets/audio/Level_Complete.m4a"),
    "r" : require("@/assets/audio/Level_Complete.m4a"),
    "s" : require("@/assets/audio/Level_Complete.m4a"),
    "t" : require("@/assets/audio/Level_Complete.m4a"),
    "u" : require("@/assets/audio/Level_Complete.m4a"),
    "v" : require("@/assets/audio/Level_Complete.m4a"),
    "w" : require("@/assets/audio/Level_Complete.m4a"),
    "x" : require("@/assets/audio/Level_Complete.m4a"),
    "y" : require("@/assets/audio/Level_Complete.m4a"),
    "z" : require("@/assets/audio/Level_Complete.m4a"),
};

export default GameLetters;