const GameLetters = {
    "a" : require("@/assets/audio/letters/a.m4a"),
    "b" : require("@/assets/audio/letters/b.m4a"),
    "c" : require("@/assets/audio/letters/c.m4a"),
    "d" : require("@/assets/audio/letters/d.m4a"),
    "e" : require("@/assets/audio/letters/e.m4a"),
    "f" : require("@/assets/audio/letters/f.m4a"),
    "g" : require("@/assets/audio/letters/g.m4a"),
    "h" : require("@/assets/audio/letters/h.m4a"),
    "i" : require("@/assets/audio/letters/i.m4a"),
    "j" : require("@/assets/audio/letters/j.m4a"),
    "k" : require("@/assets/audio/letters/k.m4a"),
    "l" : require("@/assets/audio/letters/l.m4a"),
    "m" : require("@/assets/audio/letters/m.m4a"),
    "n" : require("@/assets/audio/letters/n.m4a"),
    "o" : require("@/assets/audio/letters/o.m4a"),
    "p" : require("@/assets/audio/letters/p.m4a"),
    "q" : require("@/assets/audio/letters/q.m4a"),
    "r" : require("@/assets/audio/letters/r.m4a"),
    "s" : require("@/assets/audio/letters/s.m4a"),
    "t" : require("@/assets/audio/letters/t.m4a"),
    "u" : require("@/assets/audio/letters/u.m4a"),
    "v" : require("@/assets/audio/letters/v.m4a"),
    "w" : require("@/assets/audio/letters/w.m4a"),
    "x" : require("@/assets/audio/letters/x.m4a"),
    "y" : require("@/assets/audio/letters/y.m4a"),
    "z" : require("@/assets/audio/letters/z.m4a"),
};

export default GameLetters;